sudo: required
services:
  - docker

before_install:
  - docker build -t vilikoistinen/docker-react -f Dockerfile.dev .
  
script:
  -  docker run vilikoistinen/docker-react npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "dockerreact"
    env: "Dockerreact-env-1"
    bucket_name: "elasticbeanstalk-eu-west-1-102430186019"
    bucket_path: "dockerreact"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"