sudo: required
services:
  - docker

before_install:
  - docker build -t vilikoistinen/docker-react -f Dockerfile.dev .
  
script:
  -  docker run vilikoistinen/docker-react npm run test -- -- coverage