sudo: required
services:
  - docker

before_install:
  - docker build -t vilikoistinen/docker-react -f Dockerfile.dev .
  
script:
  -  docker run vilikoistinen/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
  secure: "$SECRETACCESSKEY"
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-102430186019"
  bucket_path: "docker-react"
  on:
    branch: master